#-------------#
# Import Vars #
#-------------#
Import('*')

#---------#
# Sources #
#---------#
src = Split("""control_list
               fontspacing.1
               fontspacing.2
               keys
               videomodes""")

#---------------------------------#
# Distribute to src_dir & bin_dir #
#---------------------------------#
dist_files = ['SConscript'] + src

env.Distribute (src_dir, dist_files)
env.Distribute (bin_dir, src)

#--------------------#
# Install data files #
#--------------------#
env.Install('%s/lists' % prefix, src)

Export(['env', 'prefix', 'src_dir', 'bin_dir'])

SConscript('menus/SConscript')
