#-------------#
# Import Vars #
#-------------#
import os, sys
Import('*')

#----------------#
# Subdirectories #
#----------------#
#vamosobjs = SConscript('vamos/SConscript', exports=['env','src_dir'])

#---------#
# Sources #
#---------#
src = Split("""main.cpp
               camera.cpp
               font.cpp
               joepack.cpp
               keyman.cpp
               messageq.cpp
               model.cpp
               mouse.cpp
               objects.cpp
               quat.cpp
               settings.cpp
               track.cpp
               utility.cpp
               configfile.cpp
               bezier.cpp""")

#------------------------#
# Copy Build Environment #
#------------------------#
local_env = env.Copy()
SConsignFile()

#--------------------------#
# Modify Build Environment #
#--------------------------#
#if sound == 'openal':
#    local_env.Append(CCFLAGS = '-DHAVE_OPENAL=1')
#else:
#    local_env.Append(CCFLAGS = '-DHAVE_FMOD=1')

if ( 'win32' == sys.platform or 'cygwin' == sys.platform ):
    local_env.Append(LIBPATH = ['/usr/lib/mingw'])
    local_env.Append(LIBS = ['opengl32', 'glu32', 'glew32', 'mingw32', 'SDLmain', 'SDL', 'SDL_image' ])
else:
    local_env.ParseConfig('sdl-config --cflags --libs')
    local_env.Append(LIBPATH = ['/usr/X11R6/lib'])
    local_env.Append(LIBS = ['GL', 'GLU', 'SDL_image'])
	
local_env.Append(CCFLAGS = ['-DVERSION=\\"%s\\"' % version])

#-----------------------#
# Distribute to src_dir #
#-----------------------#
dist_files = ['SConscript'] + src

env.Distribute (src_dir, dist_files)

#--------------------#
# Compile Executable #
#--------------------#
vdrift = local_env.Program('vdrift', [src])

Default(vdrift)

#---------#
# Install #
#---------#
#local_env.Install(bin, vdrift)
